name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start containers
      run: docker-compose -f "./desafios_docker/desafio_node/docker-compose.yml" up -d --build
